//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class CallbackBase : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CallbackBase(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CallbackBase obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CallbackBase() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MyDLLPINVOKE.delete_CallbackBase(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual void Callback(string str, FloatVector fVect) {
    MyDLLPINVOKE.CallbackBase_Callback(swigCPtr, str, FloatVector.getCPtr(fVect));
    if (MyDLLPINVOKE.SWIGPendingException.Pending) throw MyDLLPINVOKE.SWIGPendingException.Retrieve();
  }

  public CallbackBase() : this(MyDLLPINVOKE.new_CallbackBase(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("Callback", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateCallbackBase_0(SwigDirectorMethodCallback);
    MyDLLPINVOKE.CallbackBase_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(CallbackBase));
    return hasDerivedMethod;
  }

  private void SwigDirectorMethodCallback(string str, global::System.IntPtr fVect) {
    Callback(str, new FloatVector(fVect, false));
  }

  public delegate void SwigDelegateCallbackBase_0(string str, global::System.IntPtr fVect);

  private SwigDelegateCallbackBase_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(string), typeof(FloatVector) };
}
