//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MyDLL {
  public static CppClass CreateInstance() {
    global::System.IntPtr cPtr = MyDLLPINVOKE.CreateInstance();
    CppClass ret = (cPtr == global::System.IntPtr.Zero) ? null : new CppClass(cPtr, false);
    return ret;
  }

}
